### ISSUE TITLE
client error

### ISSUE THREAD

**Issue by noy98** [AeronicaMC/mxTune#2]
[00:51:41] [MiniServServer/WARN]: Could not read data from client
java.io.IOException: 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다
        at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_201]
        at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[?:1.8.0_201]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[?:1.8.0_201]
        at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:1.8.0_201]
        at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:1.8.0_201]
        at net.montoyo.wd.miniserv.server.Server.loopUnsafe(Server.java:168) [Server.class:?]
        at net.montoyo.wd.miniserv.server.Server.run(Server.java:114) [Server.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

**Comment by Aeronica** [comment]
The current connection was forcibly closed by the remote host = 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다

I need the full log. There are mxTune classes referenced.
전체 로그가 필요합니다. mxTune 클래스가 참조되었습니다.

Paste sites and their limits:
https://hastebin.com/ 400KB
https://pastebin.com/: 512KB as guest, 10MB as Pro ($$$) 
https://paste.ee/: 1MB as guest, 6MB as member (Free)
https://gist.github.com/: 100MB Requires member (Free)
https://paste.gg/: 15MB

**Comment by Aeronica** [comment]
No response to log request.

**Comment by Aeronica** [comment]
No response to logs request.
